db:
  image: mysql:5.5
  ports:
   - '3306:3306'
  environment:
    MYSQL_ROOT_PASSWORD: dev
    MYSQL_DATABASE: meran
  container_name: meran32_db
app:
  build: .
  ports:
   - '80:80'
   - '443:443' 
  links:
   - db
  environment:
    MERAN_CONF: '/etc/meran/meranmain.conf'
    DB_NAME: meran
    DB_USER: root
    DB_PASS: dev
    DB_HOST: db
  container_name: meran32_app
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - '8080:80'
  links:
   - db:mysql
  environment:
    MYSQL_ROOT_PASSWORD: dev
  container_name: meran32_phpmyadmin