#!/bin/bash
set -e
# Instalar dependencias

# Copiar al volumen la configuracion
CONFIG_DIR=/etc/meran
ID=main
DB_USER=meran
DB_PASS=meranpass
DB_HOST=mysql
DB_NAME=meran
MERAN_PATH=/usr/local/share/meran
MAIN_CONFIG=$CONFIG_DIR/meran$ID.conf
TPL_MAIN_CONFIG=$MERAN_PATH/docs/instalador/meran.conf
TPL_INIT_SCRIPT=$MERAN_PATH/docs/instalador/iniciando.pl
INIT_SCRIPT=$CONFIG_DIR/iniciando$ID.pl
TPL_APACHE_CONF_OPAC=$MERAN_PATH/docs/instalador/debian6/apache-jaula-opac
TPL_APACHE_CONF_SSL=$MERAN_PATH/docs/instalador/debian6/apache-jaula-ssl
APACHE_CONF_OPAC=/etc/apache2/sites_enabled/opac.conf
APACHE_CONF_SSL=/etc/apache2/sites_enabled/ssl.conf
SPHINX_CONFIG_DIR=$MERAN_PATH/$ID/sphinx/etc
SPHINX_CONFIG=$SPHINX_CONFIG_DIR/sphinx.conf
TPL_SPHINX_CONFIG=$MERAN_PATH/docs/instalador/sphinx.conf

[ -d $MERAN_PATH ] || ( echo "El directorio $MERAN_PATH debe existir"; exit 1 )

[ -d $MERAN_PATH/$ID ] || mkdir $MERAN_PATH/$ID

[ -L $CONFIG_DIR ] || ln -s $CONFIG_DIR /meran/config
[ -L $/var/logs/meran ] || ln -s /var/logs/meran /meran/logs
[ -L $MERAN_PATH/$ID/files ] || ln -s $MERAN_PATH/$ID/files /meran/files
[ -d /etc/apache2/sites_enabled ] && rm -fr /etc/apache2/sites_enabled
[ -L /etc/apache2/sites_enabled ] || ln -s /etc/apache2/sites_enabled/ /meran/apache

if [ ! -f $MAIN_CONFIG ]; then
  # Configuracion principal de meran
  [ -f $TPL_MAIN_CONFIG ] || ( echo "El archivo $TPL_MAIN_CONFIG debe existir"; exit 1 )
  [ -d $CONFIG_DIR ] || mkdir -p $CONFIG_DIR
  sed s@reemplazarID@$ID@g $TPL_MAIN_CONFIG > $MAIN_CONFIG
  sed -i s@reemplazarUSER@$DB_USER@g $MAIN_CONFIG
  sed -i s@reemplazarPASS@$DB_PASS@g $MAIN_CONFIG
  sed -i s@reemplazarBDDHOST@$DB_HOST@g $MAIN_CONFIG
  sed -i s@reemplazarDATABASE@$DB_NAME@g $MAIN_CONFIG
  sed -i s@reemplazarPATHBASE@$MERAN_PATH@g  $MAIN_CONFIG
fi

if [ ! -f $INIT_SCRIPT ]; then
  # Configuracion del script de inicio
  [ -f $TPL_INIT_SCRIPT ] || ( echo "El archivo $TPL_INIT_SCRIPT debe existir"; exit 1 )
  sed s@reemplazarID@$ID@g $TPL_INIT_SCRIPT > $INIT_SCRIPT
  sed -i s@reemplazarCONFMERAN@$CONFIG_DIR@g $INIT_SCRIPT
  sed s@reemplazarPATHBASE@$MERAN_PATH@g $INIT_SCRIPT
fi

if [ ! -f $SPHINX_CONFIG ]; then
  [ -d $SPHINX_CONFIG_DIR ] || mkdir $SPHINX_CONFIG_DIR
  sed s@reemplazarID@$ID@g $TPL_SPHINX_CONFIG > $SPHINX_CONFIG
  sed -i s@reemplazarIUSER@$DB_USER@g $SPHINX_CONFIG
  sed -i s@reemplazarIPASS@$DB_PASS@g $SPHINX_CONFIG
  sed -i s@reemplazarBDDHOST@$DB_HOST@g $SPHINX_CONFIG
  sed -i s@reemplazarDATABASE@$DB_NAME@g $SPHINX_CONFIG
fi

if [ ! -f $APACHE_CONF_SSL ]; then
  cp $TPL_APACHE_CONF_SSL $APACHE_CONF_SSL
fi

if [ ! -f $APACHE_CONF_OPAC ]; then
  cp $TPL_APACHE_CONF_OPAC $APACHE_CONF_OPAC
fi

chown www-data:www-data -R /meran
chown www-data:www-data -R $MERAN_PATH
$SPHINX_BIN/indexer -c $SPHINX_CONFIG --all --rotate

#CONSIDERAR los crons en la maquina host así como la rotacion de logs en el volumen
#INDICAR EN EL README COMO SE INSTALA A PARTIR DE UNA DB pre-existente con los datos necesarios
